"""initial schema

Revision ID: 9168bb41f184
Revises: 
Create Date: 2026-08-24 11:04:29.538792
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9168bb41f184'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_functions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_business_functions')),
    sa.UniqueConstraint('name', name=op.f('uq_business_functions_name'))
    )
    with op.batch_alter_table('business_functions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_business_functions_code'), ['code'], unique=True)

    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies')),
    sa.UniqueConstraint('name', name=op.f('uq_companies_name'))
    )
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments')),
    sa.UniqueConstraint('name', name=op.f('uq_departments_name'))
    )
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_departments_code'), ['code'], unique=True)

    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('country', sa.String(length=80), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stores')),
    sa.UniqueConstraint('name', 'country', name=op.f('uq_stores_name'))
    )
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('seniority', sa.Enum('ASSISTANT', 'JUNIOR', 'SEMI_SENIOR', 'SENIOR', 'LEAD', name='seniority', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_positions_department_id_departments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_positions')),
    sa.UniqueConstraint('department_id', 'title', name=op.f('uq_positions_department_id'))
    )
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_positions_department_id'), ['department_id'], unique=False)

    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('country', sa.String(length=80), nullable=False),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('internal_email', sa.String(length=160), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='employeestatus', native_enum=False, create_constraint=True), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], name=op.f('fk_employees_position_id_positions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employees'))
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employees_internal_email'), ['internal_email'], unique=True)
        batch_op.create_index(batch_op.f('ix_employees_position_id'), ['position_id'], unique=False)

    op.create_table('position_functions',
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('business_function_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['business_function_id'], ['business_functions.id'], name=op.f('fk_position_functions_business_function_id_business_functions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], name=op.f('fk_position_functions_position_id_positions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('position_id', 'business_function_id', name=op.f('pk_position_functions'))
    )
    op.create_table('user_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'DEPARTMENT_HEAD', 'COLLABORATOR', name='userrole', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_user_accounts_employee_id_employees')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_accounts')),
    sa.UniqueConstraint('employee_id', name=op.f('uq_user_accounts_employee_id'))
    )
    with op.batch_alter_table('user_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_accounts_username'), ['username'], unique=True)

    op.create_table('auth_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_accounts.id'], name=op.f('fk_auth_sessions_user_id_user_accounts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_sessions'))
    )
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_sessions_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_sessions_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_auth_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('credit_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.Enum('USD', 'VES', name='currency', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('requesting_department_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='creditnotestatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_credit_notes_amount_positive')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_credit_notes_company_id_companies')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user_accounts.id'], name=op.f('fk_credit_notes_created_by_user_id_user_accounts')),
    sa.ForeignKeyConstraint(['requesting_department_id'], ['departments.id'], name=op.f('fk_credit_notes_requesting_department_id_departments')),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_credit_notes_store_id_stores')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credit_notes'))
    )
    with op.batch_alter_table('credit_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credit_notes_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_notes_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index('ix_credit_notes_department_status', ['requesting_department_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_notes_requesting_department_id'), ['requesting_department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_notes_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_notes_store_id'), ['store_id'], unique=False)

    op.create_table('credit_note_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credit_note_id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('CREATED', 'APPROVED', 'REJECTED', name='creditnoteaction', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('previous_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='creditnotestatus', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('new_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='creditnotestatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['user_accounts.id'], name=op.f('fk_credit_note_events_actor_user_id_user_accounts')),
    sa.ForeignKeyConstraint(['credit_note_id'], ['credit_notes.id'], name=op.f('fk_credit_note_events_credit_note_id_credit_notes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credit_note_events'))
    )
    with op.batch_alter_table('credit_note_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credit_note_events_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_note_events_credit_note_id'), ['credit_note_id'], unique=False)
        batch_op.create_index('ix_credit_note_events_note_time', ['credit_note_id', 'occurred_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_note_events', schema=None) as batch_op:
        batch_op.drop_index('ix_credit_note_events_note_time')
        batch_op.drop_index(batch_op.f('ix_credit_note_events_credit_note_id'))
        batch_op.drop_index(batch_op.f('ix_credit_note_events_actor_user_id'))

    op.drop_table('credit_note_events')
    with op.batch_alter_table('credit_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credit_notes_store_id'))
        batch_op.drop_index(batch_op.f('ix_credit_notes_status'))
        batch_op.drop_index(batch_op.f('ix_credit_notes_requesting_department_id'))
        batch_op.drop_index('ix_credit_notes_department_status')
        batch_op.drop_index(batch_op.f('ix_credit_notes_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_credit_notes_company_id'))

    op.drop_table('credit_notes')
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_auth_sessions_token_hash'))
        batch_op.drop_index(batch_op.f('ix_auth_sessions_expires_at'))

    op.drop_table('auth_sessions')
    with op.batch_alter_table('user_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_accounts_username'))

    op.drop_table('user_accounts')
    op.drop_table('position_functions')
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employees_position_id'))
        batch_op.drop_index(batch_op.f('ix_employees_internal_email'))

    op.drop_table('employees')
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_positions_department_id'))

    op.drop_table('positions')
    op.drop_table('stores')
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_departments_code'))

    op.drop_table('departments')
    op.drop_table('companies')
    with op.batch_alter_table('business_functions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_functions_code'))

    op.drop_table('business_functions')
    # ### end Alembic commands ###

